### ISSUE TITLE
Thread-safe kmer and annotation lookup?

### ISSUE THREAD

**Issue by masakistan** [GuillaumeHolley/BloomFilterTrie#10]
Thanks so much for the great library, it's helped us quite a bit!

I was wanting to parallelize some of my code but am unsure if the accessor methods are thread-safe.

The specific methods I'm wondering about are:

- `get_annotation`
- `get_list_id_genomes`
- `get_count_id_genomes`
- `get_kmer`

Could you specify if they are thread-safe?

Thanks!

**Comment by GuillaumeHolley** [comment]
Hi there :)

I'm quite happy the BFT helped you! Unfortunately, the BFT was not implemented as a parallelized library and I'm afraid all the methods you just cited are not thread-safe :(

Best, Guillaume
