### ISSUE TITLE
Extracting file name using genome id

### ISSUE THREAD

**Issue by Colelyman** [GuillaumeHolley/BloomFilterTrie#7]
Hey Guillaume,

I am trying to access the file names that correspond to the genomes that constitute the BFT. Do the genome ids provided by the `get_list_id_genomes(BFT_annotation*, BFT*)` method correspond to the indexes in the `filenames` data member of the `BFT_Root`?

For example, if one has `uint32_t* genomeIds = get_list_id_genomes(...);` then one can extract the corresponding file name of the first genome id by something like: `bft_root->filenames[genomeIds[1]]`.

Also, just out of curiosity, are there any guarantees concerning the ordering of `genomeIds`? Will the array always be sorted?

Thanks,
Cole

**Comment by GuillaumeHolley** [comment]
Hi Cole,

You are entirely right about how to access the names corresponding to the genomes that constitute the BFT :)

As far as I can remember, it is guaranteed that the ids obtained through `get_list_id_genomes(BFT_annotation*, BFT*)` are always sorted.

Have a good day!

Best, Guillaume.

**Comment by Colelyman** [comment]
Thank you so much!
